### ISSUE TITLE
Problem linking libagui_allegro5.dylib on OSX 10.7.5

### ISSUE THREAD

**Issue by fricy** [jmasterx/Agui#1]
I'm trying to build [Isoworld](https://github.com/JapaMala/isoworld) on OSX 10.7.5. Isoworld depends on Allegro5 and Agui, allegro libraries are provided, but I need to compile agui to make it work.  
I can build libagui_allegro5.a and libagui.a, but when using these libs linking Isoworld fails with [Undefined symbols for architecture i386:](http://pastebin.com/C0RgD1Tf)

```
file libagui_allegro5.a 
libagui_allegro5.a: Mach-O universal binary with 2 architectures
libagui_allegro5.a (for architecture x86_64):   current ar archive random library
libagui_allegro5.a (for architecture i386): current ar archive random library
file libagui.a 
libagui.a: Mach-O universal binary with 2 architectures
libagui.a (for architecture x86_64):    current ar archive random library
libagui.a (for architecture i386):  current ar archive random library
```

If I try to build Agui as a shared library building libagui.dylib is succefull, but [linking of libagui_allegro5.dylib fails](http://pastebin.com/GqbfbiPs), no matter if I try to build it against i386, x86_64, or both.
Any ideas what am I missing?

**Comment by jmasterx** [comment]
Hi

What version of the Agui source code are you using?  Isoworld does not include Agui's actual source files so if you compile only the headers you will get undefined symbol errors. If that is the case, start from the master branch I have here on GitHub.

Otherwise, I am not sure what the problem could be. I compile Agui by generating an XCode project with CMAKE and building the .a files in XCode.

**Comment by fricy** [comment]
Yeah, Isoworld doesn't provide the libraries, so I'm trying to build it from your sources here, generating with CMAKE and building with clang 4.2 (clang-425.0.28), but no xcode. Also tried gcc 4.5, but didn't help.  

.a files build succesfully, but linking Isoworld fail with [Undefined symbols for architecture i386:](http://pastebin.com/bZD42zEy). (The vtable messages were a user error, gone now.)  
I'd ask help from Isoworld's author, but I suspect the problem is in agui, as I fail building libagui_allegro5.dylib, and the [resulting error message](http://pastebin.com/GqbfbiPs) is partly similar to that produced by Isoworld.  
Already tried building Agui against allegro5.0.7 headers provided by Isoworld and [latest allegro 5.1.10 source](https://github.com/liballeg/allegro5), but it doesn't make a difference.

**Comment by jmasterx** [comment]
I could send you my .a binaries, but they are built on OSX 10.9.4 with XCode 6.

Though they target 10.6 and up.
